title: Forbesii
email: simon.gray@forbesii.com
description: > # this means to ignore newlines until "baseurl:"
  Tital blog created for personal use
  Inspiration come from somewhere

baseurl: "/blog" # the subpath of your site, e.g. /blog

url: "https://simon-gray.github.io/" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

collections:
  episodes:
    output: true
  seasons:
    output: true
  characters:
    output: true

defaults:
  - scope:
      path: ""
      type: "episodes"
    values:
      layout: "episode"
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "character"
  - scope:
      path: ""
      type: "seasons"
    values:
      layout: "season"

gems:
  - octopress-paginate
